
name: Test Manual Check Run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'My check name',
                head_sha: '${{github.sha}}',
                owner: "elbrenn",
                repo: "actions-checks-test",
                status: "in_progress",
                started_at: new Date()
            });

